lib/typedefs.ts, test/extend.test.ts
Ensure scoped query methods that accept a `selector` option have the correct type for the `options` parameter (`SelectorMatcherOptions` instead of `MatcherOptions` from **@testing-library/dom**).
=> Use options interface that includes selector for extend queries

.travis.yml, lib/extend.ts, package.json, yarn.lock
Augment types and prototypes from `playwright` instead of `playwright-core` (see: https://github.com/microsoft/playwright/commit/505d94ab1ac1a5bec8a76492e5c1acbc5b100452).
=> Update/add support for Playwright 1.1.0

README.md, lib/index.ts, lib/typedefs.ts, test/extend.test.ts, test/fixtures/late-page.html
https://github.com/testing-library/pptr-testing-library/pull/44
=> Add find* queries (testing-library/pptr-testing-library#44)

.eslintrc.js, lib/extend.ts, lib/index.ts, lib/typedefs.ts, test/extend.test.ts, test/fixtures/page.html, yarn.lock
- Port nested RegExp feature from upstream
- Port _correct_ `RoleMatcherOptions` for upgraded **@testing-library/dom** from upstream (thanks @patrickhulce! I totally missed this)
=> Nested RegExp and proper options type for role queries

lib/index.ts, package.json, test/__snapshots__/extend.test.ts.snap, test/extend.test.ts, test/serializers/stacktrace.ts, yarn.lock
- Upgrade Playwright to 1.9.1
- Strip any Playwright-related prefix (i.e: `jsHandle.evaluateHandle:` and `Evaluation Failed:`) from element errors
- Use snapshot serializer + snapshot error matcher instead of try/catch
=> 💚 Upgrade Playwright to 1.9 + improve error output

lib/index.ts
Use type definition from library that provides \`waitFor\` functionality [**wait-for-expect**](https://github.com/TheBrainFamily/wait-for-expect) to type `callback` parameter of `waitFor`. This allows `async` functions to be passed as the `callback`.
=> 🐛 Fix callback type in `waitFor`

jest.config.js, package.json, yarn.lock
- Remove **ts-jest**, it's provided by **@hover/javascript** now
- Update semver ranges in package.json
=> 🛠 Update semver ranges for development dependencies

README.md
The example is missing the `async` keyword
=> Add missing async keyword in README

package.json, test/fixture/fixture.test.ts, test/standalone/index.test.ts
Expose `configure` from `/fixture` package entry.
- Improve test coverage of standalone queries.
=> ✨ Expose configure API on fixture entrypoint

.eslintrc.js, README.md, test/fixture/fixture.test.ts, test/fixtures/page.html
Update scoping example in fixture section with correct usage.
- Make scoping test case more representative of the intended usage
- Disable irrelevant ESLint rule via `overrides` instead of comment for fixture tests
=> 📝 Fix scoping example in fixture documentation

lib/index.ts, lib/typedefs.ts, test/standalone/index.test.ts
Add support for the `asyncUtilsTimeout` configuration option via the `configure()` API so that the timeout for **findBy*** queries can be configured globally.
Closes #460
=> ✨ Support timeout configuration option

lib/common.ts, lib/fixture/index.ts, lib/fixture/locator/fixtures.ts, lib/fixture/locator/helpers.ts, lib/fixture/locator/index.ts, lib/fixture/types.ts, lib/index.ts, lib/typedefs.ts, package.json, test/fixture/configure.test.ts, test/fixture/element-handles.test.ts, test/fixture/locators.test.ts
Implement `configure` API for locator-based queries via `test.use`.
```ts
// playwright.config.ts
import type { PlaywrightTestConfig } from '@playwright/test';
const config: PlaywrightTestConfig = {
use: {
testIdAttribute: 'data-custom-test-id',
asyncUtilsTimeout: 5000,
},
};
export default config;
```
```ts
import { test as baseTest } from '@playwright/test'
import {
locatorFixtures as fixtures,
LocatorFixtures as TestingLibraryFixtures,
within
} from '@playwright-testing-library/test/fixture';
const test = baseTest.extend<TestingLibraryFixtures>(fixtures);
const {expect} = test;
// Entire test suite
test.use({ testIdAttribute: 'data-custom-test-id' });
test.describe(() => {
// Specific block
test.use({
testIdAttribute: 'some-other-test-id',
asyncUtilsTimeout: 5000,
});
test('my form', …
```
=> ✨ Support the configure API for locator queries

lib/fixture/locator/fixtures.ts, lib/fixture/locator/helpers.ts, lib/fixture/types.ts, test/fixture/element-handles.test.ts, test/fixture/locators.test.ts
Refactors extracted from #488 to clean up the diff:
- Isolate 'standard' page (no timeout) in `describe` block so that both standard and deferred page tests have `beforeEach` and `afterEach` to open and close the page
- Rename `SupportedQueries` to `SynchronousQueries` in preparation to support `find*` queries
- Use queries from Testing Library to enumerate queries (instead of internal hard-coded query name array, with the intention of removing all of the legacy ElementHandle implementation in a future major release)
=> ♻️ Refactors from locator find query branch

README.md, lib/fixture/index.ts, lib/fixture/locator/fixtures.ts, lib/fixture/locator/helpers.ts, lib/fixture/locator/index.ts, lib/fixture/types.ts, lib/index.ts, test/fixture/locators.test.ts, test/fixtures/late-page.html
> #### ~Refactors~ Merged in #489 
> - Isolate 'standard' page (no timeout) in `describe` blocks
> - Use `queries` from Testing Library to enumerate queries (instead of internal hard-coded query name array, with the intention of removing all of the legacy `ElementHandle` implementation in a future major release)
=> ✨ Add support for find queries in locator fixture

lib/fixture/locator/fixtures.ts, lib/fixture/locator/helpers.ts, lib/fixture/locator/queries.ts, test/fixture/element-handles.test.ts, test/fixture/locators.test.ts, test/fixtures/late-page.html, test/standalone/index.test.ts
- test: speed up tests by only delaying 'late page' by 2 seconds
- refactor(fixture): split query-related stuff out into separate module
=> ♻️ Speed up tests, split out query helpers

lib/fixture/index.ts, lib/fixture/locator/fixtures.ts, lib/fixture/locator/helpers.ts, lib/fixture/locator/index.ts, lib/fixture/types.ts, test/fixture/locators.test.ts
Thanks to @gajus for the [inspiration](https://github.com/testing-library/playwright-testing-library/issues/430#issuecomment-1227650435) here. This adds a `screen` fixture that combines Playwrights `page` API with the document-scoped Testing Library queries (`queries`). This will likely replace `queries` altogether in the official release of this stuff.
```ts
test('screen fixture responds to Page and Query methods', async ({screen}) => {
const locator = screen.getByRole('button', {name: /getBy.*Test/})
expect(await locator.textContent()).toEqual('getByRole Test')
await screen.goto(`file://${path.join(__dirname, '../fixtures/late-page.html')}`)
const delayedLocator = await screen.findByText('Loaded!', undefined, {timeout: 3000})
expect(await delayedLocator.textContent()).toEqual('Loaded!') …
```
=> ✨ Add screen fixture API that combines queries with Page API

lib/fixture/locator/index.ts, lib/fixture/locator/queries.ts, test/fixture/locators.test.ts
Surface a ~less confusing error~ the original Playwright timeout error in the case an element is being waited upon via a `find*` query and it times out due to being hidden but still selectable. In this case we can't surface a Testing Library `get*` query error because it still finds the element. Right now that fails in the form of a hard-coded `100ms` Playwright `waitFor()`.
- ~Bump down the delay on the "late page" to speed up the tests a bit~ #495
=> 🐛 Don't surface 100ms timeout errors

README.md, test/fixture/locators.test.ts, test/fixtures/late-page.html
Clarify that the `findBy` queries for the `Locator` fixture return `Promise<Locator>` and their intended usage.
=> 📝 Add documenation clarifying asynchronous locator queries

.github/workflows/build.yml, lib/fixture/helpers.ts, test/fixture/locators.test.ts
Our types incorrectly claimed support for function [`TextMatch`](https://testing-library.com/docs/queries/about/#textmatch). This change actually adds support for that.
=> 🐛 Support function text matchers in queries

.github/workflows/build.yml
Playwright dropped support for Node 12 in a non-breaking release, but
it's leaving LTS soon anyways.
=> 👷🏻‍♀️ Bmp Node versions up an LTS

README.md, lib/fixture/helpers.ts, lib/fixture/locator/fixtures.ts, lib/fixture/locator/helpers.ts, package.json, playwright.config.ts, test/fixture/locators.test.ts
Because we're (rudimentarily) serializing `TextMatch` functions, they can't reference outer closure scope.
```ts
// ✅ This is supported
screen.getByText(content => content.startsWith('Foo'))
// ❌ This is not supported
const startsWithFoo = (content: string) => content.startsWith('Foo')
screen.getByText(content => startsWithFoo(content))
```
This adds a "known limitation" entry to the readme describing this limitation and attempts to detect `TextMatch` functions with external references in order to print a helpful error message.
=> 🔊 Improve error message for invalid function matchers

README.md, lib/fixture/locator/fixtures.ts, lib/fixture/locator/index.ts, lib/fixture/locator/queries.ts, lib/fixture/types.ts, playwright.config.ts, test/fixture/locators.test.ts, test/fixtures/chaining.html
> - [x] ⚠️ This depends on #498, so merge it first
Implement query chaining per response to @gajus comment https://github.com/testing-library/playwright-testing-library/pull/498#issuecomment-1241427489.
I think this came out to be pretty cool/useful/powerful.
```ts
test('chaining synchronous queries', async ({screen}) => {
const locator = screen.getByRole('figure').within().getByText('Some image')
expect(await locator.textContent()).toEqual('Some image')
})
```
```ts
test('chaining multiple asynchronous queries between synchronous queries', >
const locator = await screen // <--- including any `find*` queries makes the whole chain asynchronous
.getByTestId('modal-container') // Get "modal container" (sync)
.within()
.findByRole('dialog') // Wait for modal to appear (async, until …
```
=> ✨ Support chaining queries
